### ISSUE TITLE
No nic found in vms

### ISSUE THREAD

**Issue by shiywang** [kubevirt/demo#34]
I finally setup an minikube running three vms, it works, 
and according the setup the network topology I assume is like this
![1234](https://user-images.githubusercontent.com/6284003/35791378-341913f8-0a0d-11e8-8d4e-fa8ed5b49d49.png)

But I didn't find any network card inside the vms, when I execute `virtctl` on my localhost
```
➜  manifests git:(master) ✗ virtctl console testvm123 --kubeconfig=/home/shiywang/.kube/config 
Escape sequence is ^]
Welcome to Alpine Linux 3.5
Kernel 4.4.45-0-virtgrsec on an x86_64 (/dev/ttyS0)

localhost login: root
Welcome to Alpine!

The Alpine Wiki contains a large amount of how-to guides and general
information about administrating Alpine systems.
See <http://wiki.alpinelinux.org>.

You can setup the system with the command: setup-alpine

You may change this message by editing /etc/motd.

localhost:~# ip a
1: lo: <LOOPBACK> mtu 65536 qdisc noop state DOWN qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
localhost:~# 
```
```
➜  manifests git:(master) ✗ oc get vms        
NAME          AGE
testvm        2d
testvm123     39m
testvm12345   38m
```
vms xml dump file
```
<domain type='qemu' id='1' xmlns:qemu='http://libvirt.org/schemas/domain/qemu/1.0'>
  <name>default_testvm123</name>
  <uuid>38fc0b14-4472-4ef8-8c3d-5fe8909f3c6b</uuid>
  <metadata>
    <kubevirt xmlns="http://kubevirt.io">
      <uid>3d2cc36e-0a3a-11e8-98f4-2820fe22abcd</uid>
      <graceperiod>
        <deletionGracePeriodSeconds>0</deletionGracePeriodSeconds>
      </graceperiod>
    </kubevirt>
  </metadata>
  <memory unit='KiB'>63488</memory>
  <currentMemory unit='KiB'>62500</currentMemory>
  <vcpu placement='static'>1</vcpu>
  <resource>
    <partition>/machine</partition>
  </resource>
  <sysinfo type='smbios'>
    <system>
      <entry name='uuid'>38fc0b14-4472-4ef8-8c3d-5fe8909f3c6b</entry>
    </system>
  </sysinfo>
  <os>
    <type arch='x86_64' machine='pc-i440fx-2.10'>hvm</type>
    <boot dev='hd'/>
  </os>
  <features>
    <acpi/>
  </features>
  <clock offset='utc'/>
  <on_poweroff>destroy</on_poweroff>
  <on_reboot>restart</on_reboot>
  <on_crash>destroy</on_crash>
  <devices>
    <emulator>/usr/local/bin/qemu-system-x86_64</emulator>
    <disk type='network' device='disk'>
      <driver name='qemu' type='raw' cache='none'/>
      <source protocol='iscsi' name='iqn.2017-01.io.kubevirt:sn.42/2'>
        <host name='10.105.187.139' port='3260'/>
      </source>
      <backingStore/>
      <target dev='vda' bus='virtio'/>
      <alias name='virtio-disk0'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x04' function='0x0'/>
    </disk>
    <controller type='usb' index='0' model='piix3-uhci'>
      <alias name='usb'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x01' function='0x2'/>
    </controller>
    <controller type='pci' index='0' model='pci-root'>
      <alias name='pci.0'/>
    </controller>
    <interface type='direct'>
      <mac address='52:54:00:e7:ea:dd'/>
      <source network='default' dev='eth0' mode='bridge'/>
      <target dev='macvtap0'/>
      <model type='rtl8139'/>
      <alias name='net0'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x03' function='0x0'/>
    </interface>
    <serial type='unix'>
      <source mode='bind' path='/var/run/kubevirt-private/default/testvm123/virt-serial0'/>
      <target port='0'/>
      <alias name='serial0'/>
    </serial>
    <console type='unix'>
      <source mode='bind' path='/var/run/kubevirt-private/default/testvm123/virt-serial0'/>
      <target type='serial' port='0'/>
      <alias name='serial0'/>
    </console>
    <input type='mouse' bus='ps2'>
      <alias name='input0'/>
    </input>
    <input type='keyboard' bus='ps2'>
      <alias name='input1'/>
    </input>
    <graphics type='vnc' socket='/var/run/kubevirt-private/default/testvm123/virt-vnc'>
      <listen type='socket' socket='/var/run/kubevirt-private/default/testvm123/virt-vnc'/>
    </graphics>
    <video>
      <model type='vga' vram='16384' heads='1' primary='yes'/>
      <alias name='video0'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x0'/>
    </video>
    <memballoon model='virtio'>
      <alias name='balloon0'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x05' function='0x0'/>
    </memballoon>
  </devices>
  <seclabel type='dynamic' model='dac' relabel='yes'>
    <label>+107:+107</label>
    <imagelabel>+107:+107</imagelabel>
  </seclabel>
  <qemu:commandline>
    <qemu:env name='SLICE' value='/kubepods/besteffort/pod3d2e0c59-0a3a-11e8-98f4-2820fe22abcd/6de8ba609d7e8e5dfcc6fc06bf40f261c5e6cd0cdcf0dd395f171c731f6fd122'/>
    <qemu:env name='CONTROLLERS' value='perf_event,freezer,memory,cpuset,net_cls'/>
  </qemu:commandline>
</domain>
```

why there's no NIC in vms ?

**Comment by rmohr** [comment]
@shiywang thanks for the report. Youre image shows the right topology. You don't see the device because of `rtl8139`. The driver got removed from the alpine kernel. `e1000` works, and it will be used in the next kubevirt release. Later it will also be possible to define the network type on the api level.

You can use cirros if you like, until the next release is out:

```
apiVersion: kubevirt.io/v1alpha1
kind: VirtualMachine
metadata:
  name: testvm-nocloud
spec:
  terminationGracePeriodSeconds: 5
  domain:
    resources:
      requests:
        memory: 64M
    devices:
      disks:
      - name: registrydisk
        volumeName: registryvolume
        disk:
          dev: vda
      - name: cloudinitdisk
        volumeName: cloudinitvolume
        disk:
          dev: vdb
  volumes:
    - name: registryvolume
      registryDisk:
        image: kubevirt/cirros-registry-disk-demo:latest
    - name: cloudinitvolume
      cloudInitNoCloud:
        userDataBase64: I2Nsb3VkLWNvbmZpZwpwYXNzd29yZDogYXRvbWljCnNzaF9wd2F1dGg6IFRydWUKY2hwYXNzd2Q6IHsgZXhwaXJlOiBGYWxzZSB9Cg==
```

I hope that helps.
